name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install zsh
      run: sudo apt-get update && sudo apt-get install -y zsh

    - name: Run Zsh tests
      run: zsh ./test_lambda.zsh
